name: example
description: an example package for diana_annotation
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  copywith_annotation:
    path: ../../annotation
  meta: ^1.7.0

dev_dependencies:
  test: ^1.19.2
  very_good_analysis: ^2.4.0
