name: copywith_annotation
description: Generate copyWith methods for your model classes
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  json_annotation: ^4.3.0
  meta: ^1.7.0

dev_dependencies:
  test: ^1.19.2
  very_good_analysis: ^2.4.0
