name: copywith_plus
description: Generate copyWith methods for your model classes
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  analyzer: ^2.7.0
  build: ^2.1.1
  build_config: ^1.0.0
  copywith_annotation:
    path: ../annotation
  equatable: ^2.0.3
  meta: ^1.7.0
  source_gen: ^1.1.1
  source_helper: ^1.3.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.5
  build_test: ^2.1.4
  change_case: ^1.0.1
  generator_test:
    git: https://github.com/mrgnhnt96/generator_test
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
